### ISSUE TITLE
Is it possible to link collapsible fields : fold them all when you expand one?

### ISSUE THREAD

**Issue by roievil** [RXNT/react-json-schema-form-extras#218]
Hello,

First of all thank you very much for your work !

Everything is in the title, I would like to have only one field expanded at a time, is it possible to link collapsible fields, in order to have all the others fold when you expand one?

Thank you !

Olivier

**Comment by sneu012** [comment]
The engine does not support the feature that you've mentioned as a ui:field will only have access to its schema/ui:schema. 
Having said that, you should be able to implement a wrapper for the collapsible field and call a function via formContext to manually update the ui:schema and re-render the form. Something similar to what [CollapsibleField](https://github.com/RXNT/react-json-schema-form-extras/blob/master/src/CollapsibleField.js#L157) already does.
